POST http://127.0.0.1:9000/users/add 
Content-Type: application/json

{
    "username":"walid"
}

###
GET http://127.0.0.1:9000/users



###
POST http://127.0.0.1:9000/exercises/add 
Content-Type: application/json

{
    "username":"mohamed",
    "description":"run",
    "duration":10,
    "date":"2021-01-05T14:47:07.383Z"
}
####
POST http://127.0.0.1:9000/exercises/update/5ff4974534d93f1030f9d307
Content-Type: application/json

{
    "username":"mohamed",
    "description":"run",
    "duration":20,
    "date":"2021-01-05T14:47:07.383Z"
}
####
GET http://127.0.0.1:9000/exercises
###

GET http://127.0.0.1:9000/exercises/5ff49225177c7a37acbeecae

###

DELETE  http://127.0.0.1:9000/exercises/5ff49225177c7a37acbeecae
